import {
  Moon,
  Brain,
  Sparkles,
  Coffee,
  HelpCircle,
  Lightbulb,
  ScrollText,
  Pencil,
  GraduationCap,
  Clock,
  Flame,
  Trophy,
  Star,
  Compass,
  BookOpen,
  FileText,
  Rocket,
  Heart,
  Search,
  AlertCircle,
  CheckCircle,
  TrendingUp,
  Code,
  Eye,
  Layers,
  Unlock,
  Map,
  Wind,
  Wand2,
  Target,
  Shield,
  Gauge,
  Radio,
  Battery,
  Package,
  Anchor,
  Briefcase,
  Bug,
  ChevronRight,
  Cloud,
  Command,
  Monitor,
  Cpu,
  Cookie,
  Copy,
  Expand,
  Crown,
  Database,
  DollarSign,
  MousePointer,
  Smile,
  Dumbbell,
  PenTool,
  Microscope,
  Mountain,
  Music,
  Newspaper,
  Paintbrush,
  Puzzle,
  Globe,
  Flag,
  Feather,
  Filter,
  Gift,
  Hash,
  Inbox,
  Key,
  Layout,
  Link,
  List,
  Lock,
  LogIn,
  Mail,
  MessageCircle,
  Minus,
  Navigation,
  BarChart,
  PieChart,
  Pin,
  Play,
  Plus,
  Printer,
  RefreshCw,
  Save,
  Send,
  Settings,
  Share,
  Shuffle,
  Sliders,
  ThumbsUp,
  Timer,
  Hammer,
  Umbrella,
  Upload,
  User,
  Video,
  Wifi,
  Zap,
} from "lucide-react";

const PROMPTS = [
  { icon: Moon, text: "Late night study session?" },
  { icon: Brain, text: "What's on your mind?" },
  { icon: Sparkles, text: "Something sparked your curiosity?" },
  { icon: Coffee, text: "Fuelled up and ready to go?" },
  { icon: HelpCircle, text: "Got a question?" },
  { icon: Lightbulb, text: "Something just clicked?" },
  { icon: ScrollText, text: "Looking for a past paper?" },
  { icon: Pencil, text: "Revision time?" },
  { icon: GraduationCap, text: "Working toward something great?" },
  { icon: Clock, text: "Cutting it close?" },
  { icon: Flame, text: "On a roll?" },
  { icon: Trophy, text: "Chasing excellence?" },
  { icon: Star, text: "Aiming for Merit? Excellence?" },
  { icon: Compass, text: "Not sure where to start?" },
  { icon: BookOpen, text: "Ready to hit the books?" },
  { icon: FileText, text: "Hunting for that standard?" },
  { icon: Zap, text: "Let's make this quick." },
  { icon: Rocket, text: "Let's get started." },
  { icon: Heart, text: "You've got this." },
  { icon: Search, text: "What are we looking for today?" },
  { icon: AlertCircle, text: "Exam panic mode?" },
  { icon: CheckCircle, text: "Ready to ace this?" },
  { icon: TrendingUp, text: "Leveling up?" },
  { icon: Code, text: "Debugging your knowledge?" },
  { icon: Eye, text: "Time to focus?" },
  { icon: Layers, text: "Breaking it down?" },
  { icon: Unlock, text: "Ready to unlock something?" },
  { icon: Map, text: "Mapping your path?" },
  { icon: Wind, text: "Going with the flow?" },
  { icon: Wand2, text: "Need some magic?" },
  { icon: Target, text: "Locked in?" },
  { icon: Shield, text: "Fortifying your knowledge?" },
  { icon: Gauge, text: "Testing your limits?" },
  { icon: Radio, text: "Tuning in?" },
  { icon: Battery, text: "Charged up now?" },
  { icon: Package, text: "Ready to unpack something?" },
  { icon: Anchor, text: "Finding your anchor?" },
  { icon: Briefcase, text: "All business?" },
  { icon: Bug, text: "Found a tricky one?" },
  { icon: Cloud, text: "Head in the clouds?" },
  { icon: Command, text: "In command?" },
  { icon: Monitor, text: "Screen time study?" },
  { icon: Cpu, text: "Maximum processing?" },
  { icon: Cookie, text: "Treating yourself after this?" },
  { icon: Crown, text: "Royal effort?" },
  { icon: Database, text: "Mining for knowledge?" },
  { icon: Smile, text: "Keeping it positive?" },
  { icon: Dumbbell, text: "Flexing your brain?" },
  { icon: Globe, text: "Big picture thinking?" },
  { icon: Flag, text: "Setting a goal?" },
  { icon: Feather, text: "Light touch today?" },
  { icon: Filter, text: "Narrowing it down?" },
  { icon: Gift, text: "Knowledge is a gift." },
  { icon: Hash, text: "Running the numbers?" },
  { icon: Inbox, text: "Clearing the backlog?" },
  { icon: Key, text: "Unlocking something new?" },
  { icon: Link, text: "Connecting concepts?" },
  { icon: List, text: "Working through the list?" },
  { icon: Lock, text: "Cracking it open?" },
  { icon: Mail, text: "Sending it in?" },
  { icon: MessageCircle, text: "Thinking out loud?" },
  { icon: Navigation, text: "Finding your way?" },
  { icon: BarChart, text: "Tracking your progress?" },
  { icon: PieChart, text: "Slicing through it?" },
  { icon: Pin, text: "Pinning this down?" },
  { icon: Play, text: "Ready to play?" },
  { icon: RefreshCw, text: "Starting fresh?" },
  { icon: Save, text: "Saving the day?" },
  { icon: Send, text: "Ready to submit?" },
  { icon: Settings, text: "Fine tuning?" },
  { icon: Shuffle, text: "Mixing it up?" },
  { icon: Sliders, text: "Adjusting the approach?" },
  { icon: ThumbsUp, text: "Good vibes only." },
  { icon: Timer, text: "Racing the clock?" },
  { icon: Hammer, text: "Got the right tools?" },
  { icon: Umbrella, text: "Prepared for anything?" },
  { icon: User, text: "Just you and the papers." },
  { icon: Video, text: "Lights, camera, study?" },
  { icon: Wifi, text: "Connected and ready?" },
  { icon: Mountain, text: "Uphill from here." },
  { icon: Music, text: "Study playlist on?" },
  { icon: Newspaper, text: "Catching up?" },
  { icon: Paintbrush, text: "Painting the full picture?" },
  { icon: Puzzle, text: "Piecing it together?" },
  { icon: Microscope, text: "Getting into the detail?" },
  { icon: PenTool, text: "Crafting your approach?" },
  { icon: Expand, text: "Thinking bigger?" },
  { icon: MousePointer, text: "Click and let's go." },
  { icon: Layout, text: "Getting organised?" },
  { icon: LogIn, text: "Jumping in?" },
  { icon: ChevronRight, text: "One step at a time." },
  { icon: Plus, text: "Adding to your arsenal?" },
  { icon: Minus, text: "Simplifying things?" },
  { icon: Share, text: "Sharing the load?" },
  { icon: Upload, text: "Leveling up your grades?" },
  { icon: Printer, text: "Old school printing?" },
  { icon: DollarSign, text: "Worth every second." },
  { icon: Feather, text: "Light work." },
  { icon: Copy, text: "Note taking time?" },
];

const CHANCE = 1; // 1 in CHANCE chance to show a prompt

const LAUNCH_PROMPT =
  Math.random() < 1 / CHANCE
    ? PROMPTS[Math.floor(Math.random() * PROMPTS.length)]
    : null;

const LaunchIcon = LAUNCH_PROMPT?.icon ?? null;

export default function SearchEmptyState() {
  return (
    <div className="rounded-lg border border-dashed border-muted-foreground/50 p-12 text-center">
      {LaunchIcon && (
        <LaunchIcon className="mx-auto mb-3 text-muted-foreground" size={36} />
      )}
      <p className="text-lg font-medium text-muted-foreground">
        {LAUNCH_PROMPT?.text ?? "Ready to search"}
      </p>
      <p className="text-sm text-muted-foreground/60 mt-2">
        Enter related search terms, no need for standard ID.
      </p>
    </div>
  );
}
